language: php
php:
- 5.5
- 5.6
- 7.0
install:
- sudo apt-get -qq install coffeescript ruby-sass libyaml-dev
- npm install -g coffee-script@1.7.1
- gem install sass --version "=3.4.16"
- gem install compass --version "=1.0.1"
- bash tests/travis/install-cssmin.sh
- bash tests/travis/install-apcu.sh
- bash tests/travis/install-yaml.sh
- phpenv rehash
- pecl channel-update pecl.php.net
- travis_retry composer self-update
- travis_retry composer install --no-interaction --no-progress
before_script:
- coffee --version
- sass --version
- compass --version
script:
- phpunit --debug --testsuite AssetExtension -c phpunit.xml.dist
- phpunit -c phpunit.xml.dist
- tests/test-commands.sh
after_success:
- php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
  - vendor
notifications:
  slack:
    secure: hT6xEqww/9e0qB6KBOqdIWwehO8L5JNEuzOzOf3FemTJlB7M0yN8Mg61zNjJbLMPIsgwScWEzTP4hRpDx3rUeJDnqpSG1eMruYprKmjNW6xarIFSkKM762WgjF4jg/nMaq8PXKFIGS14G893/tfAvNUOlBr9pBDuQCDZkSMUEZY=
