language: php
php:
  - 5.3
  - 5.4

before_install:
    sudo apt-get install php5-apc
before_script:
  - phpenv rehash
  - pear channel-discover pear.corneltek.com
  - pear install -f -a corneltek/PHPUnit_TestMore
  - pear install -f -a corneltek/Universal
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - php onion install

script: phpunit
