language: php
php:
  - 5.4
  - 5.5
  - 5.6
#  - hhvm
before_install:
- sudo apt-get -qq install coffeescript ruby-sass libyaml-dev
install:
- npm install -g coffee-script
- gem install sass --version "=3.4.16"
- gem install compass --version "=1.0.1"
- bash tests/travis/install-cssmin.sh
- bash tests/travis/install-apcu.sh
- bash tests/travis/install-yaml.sh
- phpenv rehash
- travis_retry composer self-update
- travis_retry composer --profile install --no-interaction
script:
  - phpunit -c phpunit.xml.dist
  - tests/test-commands.sh
after_success:
  - php vendor/bin/coveralls -v
cache:
  apt: true
  directories:
    - vendor
notifications:
  slack:
    secure: OwI7PtL9OGmGvwJ8SRObkTvl0cMQqRssLJ+fWwrAUQ4HW/CxAg95q0jPZ4YHmUk6eFTp23HtYrV62icVUiw0dmbGOnsKBPKW5fMs8+rXTXcKi4lu5sP8lsak8ORBLcp75pagiMrviMS6nvAJO/l0U7XMGGGHJjbfyLa5bRkXdRo=
