language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_install:
  - sudo apt-get -qq install coffeescript ruby-sass libyaml-dev
before_script:
  - echo -e "yes\nno\n" | pecl -d preferred_state=beta install apcu
    # - ./bin/install-apcu.sh
    # - phpenv config-add tests/$TRAVIS_PHP_VERSION.ini
    # - phpenv config-add tests/apc.ini
    # - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m | grep apc
  - curl -o yaml-1.1.1.tgz http://pecl.php.net/get/yaml-1.1.1.tgz
  - tar -xzf yaml-1.1.1.tgz
  - sh -c "cd yaml-1.1.1 && phpize && ./configure > /dev/null && make > /dev/null && sudo make install && cd .."
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - npm install -g coffee-script
  - gem install sass --version "=3.2.12"
  - gem install compass --version "=0.12.2"
  - composer install --dev
script:
  - phpunit
  - tests/test-commands.sh
cache:
  apt: true
  directories:
    - vendor
