language: php
php:
  - 5.3
  - 5.4
before_install:
  - sudo apt-get -qq install coffeescript ruby-sass
before_script:
  - curl -o APC-3.1.13.tgz http://pecl.php.net/get/APC-3.1.13.tgz
  - tar -xzf APC-3.1.13.tgz
  - sh -c "cd APC-3.1.13 && phpize && ./configure > /dev/null && make > /dev/null && sudo make install && cd .."
  - rm -rf APC-3.1.13
  - rm APC-3.1.13.tgz
  - echo "extension=apc.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -o yaml-1.1.0.tgz http://pecl.php.net/get/yaml-1.1.0.tgz
  - tar -xzf yaml-1.1.0.tgz
  - sh -c "cd yaml-1.1.0 && phpize && ./configure > /dev/null && make > /dev/null && sudo make install && cd .."
  - rm -rf yaml-1.1.0 yaml-1.1.0.tgz
  - echo "extension=yaml.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - phpenv rehash
  - npm install -g coffee-script
  - gem install sass compass
  - pear channel-discover pear.corneltek.com
  - pear channel-discover pear.twig-project.org
  - pear channel-update pear.corneltek.com
  - pear -q install -f -a corneltek/PHPUnit_TestMore
  - pear -q install -f -a corneltek/Universal
  - pear -q install -f -a corneltek/FileUtil
  - pear -q install -f -a twig/Twig
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - php onion -q install
script: phpunit
