language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_install:
  - sudo apt-get -qq install coffeescript ruby-sass
before_script:
  - echo "no" | pecl install apcu-beta
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m | grep apc
  - curl -o yaml-1.1.1.tgz http://pecl.php.net/get/yaml-1.1.1.tgz
  - tar -xzf yaml-1.1.1.tgz
  - sh -c "cd yaml-1.1.1 && phpize && ./configure > /dev/null && make > /dev/null && sudo make install && cd .."
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - npm install -g coffee-script
  - gem install sass --version "=3.2.12"
  - gem install compass --version "=0.12.2"
  - composer install --dev
    # - pear channel-discover pear.corneltek.com
    # - pear channel-discover pear.twig-project.org
    # - pear channel-update pear.corneltek.com
    # - pear -q install -f -a corneltek/PHPUnit_TestMore
    # - pear -q install -f -a twig/Twig
    # - curl -O https://raw.github.com/phpbrew/Onion/master/onion
    # - php onion -q install
script:
  - phpunit
  - bin/assetkit init --baseDir "public/assets" --baseUrl "/assets" assetkit.yml
  - bin/assetkit add tests/assets/jquery

notifications:
  #  webbooks: "http://wireroom.extremedev.org/=/travis-ci/Hall"
