#!/bin/bash
set -e
onion -d compile \
    --lib src \
    --lib vendor/corneltek/universal/src \
    --lib vendor/corneltek/universal-cache/src \
    --lib vendor/corneltek/getoptionkit/src \
    --lib vendor/corneltek/fileutil/src \
    --lib vendor/corneltek/configkit/src \
    --lib vendor/twig/twig/lib \
    --lib vendor/symfony/yaml/Symfony/Component/Yaml \
    --lib vendor/corneltek/cliframework/src \
    --exclude Tests \
    --classloader \
    --bootstrap scripts/assetkit.php \
    --executable \
    --output assetkit.phar
mv assetkit.phar assetkit
chmod +x assetkit
