#!/bin/bash
onion -d compile \
    --lib src \
    --lib vendor/pear \
    --classloader \
    --bootstrap bin/assetkit \
    --executable \
    --output assetkit.phar
mv assetkit.phar assetkit
chmod +x assetkit
